"""
Django settings for pasportars project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============== БАЗОВЫЕ НАСТРОЙКИ ==============

# В продакшене лучше хранить в переменной окружения,
# но чтобы локально всё работало — оставим запасной вариант.
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-zg8z4x@jb+r16e_x6)n0l0)*+fa=&5$!1&%9u8xx85qzku12g2",
)

# DEBUG берём из env, по умолчанию True (локальная разработка)
DEBUG = os.getenv("DEBUG", "True") == "True"

# ALLOWED_HOSTS: локальные + из env DJANGO_ALLOWED_HOSTS
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
extra_hosts = os.getenv("DJANGO_ALLOWED_HOSTS")
if extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in extra_hosts.split(",") if h.strip()]


# ============== ПРИЛОЖЕНИЯ ==============

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
]


# ============== MIDDLEWARE ==============

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # для статики на Render
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "pasportars.urls"


# ============== ШАБЛОНЫ ==============

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # можно добавить BASE_DIR / "templates", если будут общие шаблоны
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "pasportars.wsgi.application"


# ============== БАЗА ДАННЫХ ==============
# Для Render сейчас остаётся sqlite3 (диск там персистентный для Web Service).
# Потом можно вынести в PostgreSQL.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ============== ПАРОЛИ ==============

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============== ЛОКАЛЬ / ВРЕМЯ ==============

LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Kyiv"

USE_I18N = True
USE_TZ = True


# ============== СТАТИКА ==============

STATIC_URL = "/static/"

# Куда collectstatic будет складывать файлы на сервере (Render)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Если у тебя есть папка static в корне проекта — можно подключить:
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise будет выдавать статику с кешированием
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ============== ПРОЧЕЕ ==============

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
